# TrustSeal contract — reference copy from https://github.com/lobinni/TrustSeal
# Deployed at: 0x11937A11f341Fc956c397A81D42d2F3Bff1a379c (Studionet)
# Canonical source: https://github.com/lobinni/TrustSeal/blob/main/contracts/trust_seal.py
#
# GNS only reads get_identity() from this contract to display proof-health
# badges on .gen name profile pages. The full TrustSeal verification flow
# (request_verification, complete_verification, reverify_platform, etc.)
# is handled by the standalone TrustSeal frontend at:
# https://github.com/lobinni/TrustSeal
#
# This stub exists so that gltest can deploy a local instance for
# integration tests. The full contract source is maintained in the
# TrustSeal repository above — do not edit this file directly.
#
# To run integration tests against this contract:
#   gltest tests/test_trustseal_integration.py
